### ISSUE TITLE
Cant login in the bot.

### ISSUE THREAD

**Issue by Xuchenhao** [Step7750/CSGOFloat#19] opened 2018-07-30 04:33 UTC
Hello there,

I am install this project on my server. But I found The bot cant be login, I dont receive email code 
```
[root@localhost api.csgotrade.cn]# node index.js
info: Updating Game Files...
info: Logging in bot1
debug: bot1 Generating TOTP Code from shared_secret
debug: bot1 About to connect
info: Logging in bot2
debug: bot2 About to connect
info: Listening for HTTP on port: 1739
info: Connected to the database
debug: Fetched items_game_cdn.txt
debug: Fetched csgo_english.txt
debug: Fetched items_game.txt
```

**Comment by BPatrick92** [comment] 2018-08-01 14:44
Hey, this seems to be an issue with the node-steam library dependency. For some reason, the entire server list is invalid and the only server that does work is commented out. If you don't update your server list manually - all your connections will time out and keep looping forever. Here is the issue and the temporary fix: github.com/seishun/node-steam/issues/434

**Comment by Xuchenhao** [comment] 2018-08-02 02:32
Hey, I have changed `server.js`. I am using this json `https://api.steampowered.com/ISteamDirectory/GetCMList/v1/?format=json&cellid=0`

But I get a new problem with it.

```
info: Updating Game Files...
info: Logging in bot
debug: bot Generating TOTP Code from shared_secret
debug: bot About to connect
info: Listening for HTTP on port: 1739
info: Connected to the database
debug: Fetched items_game_cdn.txt
debug: Fetched csgo_english.txt
debug: Fetched items_game.txt
info: bot Connected
error: Error logging in bot: eresult=5, eresult_extended=5, client_supplied_steamid=765611988475987**, count_loginfailures_to_migrate=0, count_disconnects_to_migrate=0
error:  Error: Disconnected
    at SteamClient._disconnected (/home/wwwroot/api.csgotrade.cn/node_modules/steam/lib/steam_client.js:186:24)
    at Connection.emit (events.js:182:13)
    at TCP._handle.close (net.js:598:12)
```

**Comment by koalayby** [comment] 2018-08-02 15:26
@BPatrick92    I have uncommon the {host: '103.28.54.11', port: 27017}, while the bot still not work. Now not clear where is the problem?  Do you know？ thanks！

**Comment by BPatrick92** [comment] 2018-08-03 17:28
@koalayby That server is no longer working, you need to grab list of all working steam official servers in order for it to work. From this website(`https://api.steampowered.com/ISteamDirectory/GetCMList/v1/?format=json&cellid=0`).

Go into `/lib/bot.js`. In the `logIn(username, password, auth, show_in_game)` function (line 22) paste
` this.servers = [{"host":"155.133.242.9","port":27018},{"host":"185.25.180.15","port":27019},{"host":"185.25.180.15","port":27018},{"host":"185.25.180.14","port":27017},{"host":"185.25.180.15","port":27017},{"host":"155.133.242.9","port":27019},{"host":"155.133.242.9","port":27017},{"host":"185.25.180.14","port":27018},{"host":"185.25.180.14","port":27019},{"host":"155.133.242.8","port":27017},{"host":"155.133.242.8","port":27018},{"host":"155.133.242.8","port":27019},{"host":"162.254.197.40","port":27018},{"host":"155.133.248.50","port":27017},{"host":"155.133.248.51","port":27017},{"host":"162.254.196.68","port":27017},{"host":"162.254.197.41","port":27017},{"host":"162.254.196.67","port":27019},{"host":"155.133.248.53","port":27018},{"host":"155.133.248.52","port":27018},{"host":"162.254.196.67","port":27017},{"host":"162.254.196.67","port":27018},{"host":"162.254.196.83","port":27017},{"host":"162.254.196.84","port":27017},{"host":"155.133.248.52","port":27017},{"host":"162.254.196.68","port":27018},{"host":"162.254.197.40","port":27019},{"host":"155.133.248.51","port":27019},{"host":"155.133.248.52","port":27019},{"host":"155.133.248.53","port":27019},{"host":"155.133.248.50","port":27019},{"host":"155.133.248.53","port":27017},{"host":"162.254.196.68","port":27019},{"host":"162.254.197.42","port":27019},{"host":"162.254.196.84","port":27018},{"host":"155.133.248.50","port":27018},{"host":"162.254.196.83","port":27019},{"host":"162.254.197.42","port":27018},{"host":"162.254.197.41","port":27018},{"host":"162.254.196.84","port":27019},{"host":"162.254.196.83","port":27018},{"host":"162.254.197.40","port":27017},{"host":"162.254.197.41","port":27019},{"host":"155.133.248.51","port":27018},{"host":"162.254.197.42","port":27017},{"host":"146.66.152.11","port":27018},{"host":"146.66.152.11","port":27019},{"host":"146.66.152.11","port":27017},{"host":"146.66.152.10","port":27019},{"host":"146.66.152.10","port":27017},{"host":"146.66.152.10","port":27018},{"host":"208.78.164.10","port":27018},{"host":"208.78.164.9","port":27019},{"host":"208.78.164.13","port":27018},{"host":"208.78.164.9","port":27017},{"host":"208.78.164.12","port":27018},{"host":"208.78.164.10","port":27017},{"host":"155.133.229.251","port":27019},{"host":"155.133.229.251","port":27017},{"host":"208.78.164.14","port":27018},{"host":"208.78.164.12","port":27019},{"host":"208.78.164.13","port":27017},{"host":"208.78.164.9","port":27018},{"host":"208.78.164.14","port":27019},{"host":"208.78.164.11","port":27018},{"host":"208.78.164.10","port":27019},{"host":"155.133.229.250","port":27017},{"host":"208.78.164.12","port":27017},{"host":"208.78.164.11","port":27019},{"host":"155.133.229.250","port":27018},{"host":"155.133.229.251","port":27018},{"host":"208.78.164.11","port":27017},{"host":"155.133.229.250","port":27019},{"host":"208.78.164.13","port":27019},{"host":"208.78.164.14","port":27017},{"host":"162.254.193.7","port":27017},{"host":"162.254.193.47","port":27019},{"host":"162.254.193.7","port":27018},{"host":"162.254.193.46","port":27018},{"host":"162.254.193.6","port":27017}];
`

And it should work.

@Xuchenhao I personally tried using 2FA/Secret key (phone) but it doesn't work for me. The email verification process specified in their documentation is working for me. 

 1. Make sure you have an account that doesn't send 2FA keys to phone but instead sends to email (the old way)

 2. Go to `config.js` and leave `auth: ""` blank but fill in the `user: "yourusername"` and `pass: "your password"` then run, you will see something like "error: Error logging in bot: eresult=5, eresult_extended=5, client_supplied_steamid=76561198134534, count_loginfailures_to_migrate=0, count_disconnects_to_migrate=0`

3. Check the email that the bot is tied to, you should get an email that says "Allow new computer" that also contains the secret/2fa. Take this secret and paste it into the `auth: ""` in `config.js`.

4. Run and you should get "`info: bot Log on OK`

**Comment by Step7750** [comment] 2018-08-05 01:26
@BPatrick92 Could you file an issue for the 2FA bug? Make sure that the system time on your computer/server is accurate. Last time I checked (a year ago), it worked fine.

I was thinking of switching to node-steam-user/node-globaloffensive since it is far more robust than node-steam/node-csgo from some other projects I've worked on. Open to PRs for this.

**Comment by vcfvct** [comment] 2018-10-05 19:41
@BPatrick92 , was struggling on this and wondering why no email triggered. Your solution works. You the man!

**Comment by Step7750** [comment] 2018-12-13 22:04
#20 Shows this is still an issue but should be fixed in https://github.com/seishun/node-steam/commit/8f0f68bc244bc02fd38c585bbe956b9546c562a0

I'll close this again when a release with this commit is published or the issue is resolved.

**Closed** 2018-12-13 23:17 UTC
